# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # vagrant plugin install vagrant-omnibus
  config.omnibus.chef_version = '11.16.4'

  config.vm.box = 'chef/ubuntu-14.04'
  config.vm.network 'private_network', ip: '192.168.51.50'

  config.vm.provider 'virtualbox' do |vb|
    vb.customize ['modifyvm', :id, '--memory', '1024']
  end

  config.vm.provision 'chef_solo' do |chef|
    chef.custom_config_path = 'Vagrantfile.chef'
    chef.roles_path = 'roles'
    chef.add_role 'base'
  end
end
